import { ruleEnabled } from "../config.js";
import type { Rule, Fix } from "./types.js";
import {
  walkElements,
  getAttr,
  hasAttr,
  renderOpenTag,
  elementLine,
} from "../parse.js";

/**
 * Alt text coverage for <img> and <input type="image">. Also catches
 * "junk" alt values that look autogenerated (filename, generic words like
 * "image" / "photo" / "picture"), since these pass a naive presence check
 * but tell a screen-reader user nothing useful.
 */

const GENERIC_ALT = new Set([
  "image",
  "img",
  "picture",
  "photo",
  "photograph",
  "graphic",
  "icon",
  "logo",
  "untitled",
]);

export const imageAltText: Rule = (ctx) => {
  const rule = ctx.config.rules.imageAltText;
  if (!ruleEnabled(rule)) return [];

  const issues = [] as ReturnType<Rule>;

  for (const el of walkElements(ctx.doc.root)) {
    const tag = el.tagName?.toLowerCase();
    const isImg = tag === "img";
    const isInputImage =
      tag === "input" && (getAttr(el, "type") ?? "").toLowerCase() === "image";
    if (!isImg && !isInputImage) continue;

    const role = getAttr(el, "role")?.toLowerCase();
    const ariaHidden = getAttr(el, "aria-hidden")?.toLowerCase() === "true";
    if (role === "presentation" || role === "none" || ariaHidden) continue;

    const ariaLabel = (getAttr(el, "aria-label") ?? "").trim();
    if (ariaLabel) continue;

    const hasAlt = hasAttr(el, "alt");
    const altVal = (getAttr(el, "alt") ?? "").trim();
    const src = getAttr(el, "src") ?? "unknown";

    if (!hasAlt) {
      const fix = isImg ? buildAltFix(el, ctx.source) : undefined;
      issues.push({
        id: "image-alt-text",
        severity: rule.severity,
        message: isInputImage
          ? `<input type="image" src="${src}"> is missing alt (treated as a button by screen readers).`
          : `<img src="${src}"> is missing alt attribute.`,
        element: renderOpenTag(el),
        suggestion: isInputImage
          ? `Add alt="Search" (or a label for the action this image-button triggers).`
          : `Add alt="description" or alt="" + role="presentation" if purely decorative.`,
        line: elementLine(el),
        ...(fix ? { fix } : {}),
      });
      continue;
    }

    if (altVal === "") {
      // Empty alt is valid for decorative <img>. <input type="image"> with
      // empty alt is still a problem — it's a submit button with no label.
      if (isInputImage) {
        issues.push({
          id: "image-alt-text",
          severity: rule.severity,
          message: `<input type="image" src="${src}"> has empty alt. Image buttons must announce their action.`,
          element: renderOpenTag(el),
          suggestion: `Set alt to describe the button's action, e.g. alt="Search".`,
          line: elementLine(el),
        });
        continue;
      }
      issues.push({
        id: "image-alt-text",
        severity: rule.severity,
        message: `<img src="${src}"> has empty alt. Mark it with role="presentation" if decorative, otherwise provide meaningful alt text.`,
        element: renderOpenTag(el),
        suggestion: `Add role="presentation" if decorative, or supply descriptive alt text.`,
        line: elementLine(el),
      });
      continue;
    }

    if (looksGeneric(altVal, src)) {
      issues.push({
        id: "image-alt-text",
        severity: rule.severity,
        message: `alt="${altVal}" is not descriptive enough (looks auto-generated or filename-like).`,
        element: renderOpenTag(el),
        suggestion: `Describe what the image conveys, not just that it is an image.`,
        line: elementLine(el),
      });
    }
  }
  return issues;
};

/**
 * Detect alt text that technically exists but tells users nothing:
 *   - Matches a filename (ends in an image extension).
 *   - Matches the src basename.
 *   - Is a generic stand-in ("image", "photo", "picture", etc).
 */
function looksGeneric(alt: string, src: string): boolean {
  const lower = alt.toLowerCase();
  if (GENERIC_ALT.has(lower)) return true;
  if (/\.(png|jpe?g|gif|svg|webp|avif|bmp|ico)$/i.test(alt)) return true;
  const srcBase = src.split("/").pop()?.split("?")[0]?.toLowerCase() ?? "";
  if (srcBase && (srcBase === lower || srcBase.replace(/\.[^.]+$/, "") === lower)) {
    return true;
  }
  return false;
}

function buildAltFix(
  el: import("../parse.js").Element,
  source: string
): Fix | undefined {
  const loc = (el as unknown as { sourceCodeLocation?: { startOffset?: number; startTag?: { endOffset?: number } } })
    .sourceCodeLocation;
  const startTagEnd = loc?.startTag?.endOffset;
  if (startTagEnd === undefined) return undefined;

  // Walk back past '/' and '>' and any trailing whitespace so we land on the
  // last "real" character of the tag. Insert after it.
  let insertAt = startTagEnd - 1;
  while (insertAt > 0 && (source[insertAt] === ">" || source[insertAt] === "/")) {
    insertAt--;
  }
  while (insertAt > 0 && /\s/.test(source[insertAt]!)) insertAt--;
  const insertPos = insertAt + 1;

  return {
    start: insertPos,
    end: insertPos,
    replacement: ` alt="" role="presentation"`,
    description: 'Mark image as decorative (alt="" role="presentation")',
  };
}
